apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  selector:
    matchLabels:
      app: producer-app
  replicas: 1
  template:
    metadata:
      labels:
        app: producer-app
    spec:
      containers:
        - name: producer-app
          image: viktorshilay/producer-app
          ports:
            - containerPort: 8080
          env:
            - name: spring.datasource.url
              value: jdbc:postgresql://postgres-service:5432/events_db
