apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  type: ClusterIP
  selector:
    app: consumer-app
  ports:
    - port: 8081
      targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  selector:
    matchLabels:
      app: consumer-app
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer-app
          image: viktorshilay/consumer-app
          ports:
            - containerPort: 8081
          env:
            - name: spring.kafka.bootstrap-servers
              value: kafka-service:9092


