apiVersion: v1
kind: Service
metadata:
  name: kafdrop-service
spec:
  type: NodePort
  selector:
    app: kafdrop
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop-deployment
spec:
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: kafka-service:9092

