apiVersion: v1
kind: Service
metadata:
  name: kafka-connector-service
spec:
  type: NodePort
  selector:
    app: kafka-connector
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30004

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connector-deployment
spec:
  selector:
    matchLabels:
      app: kafka-connector
  template:
    metadata:
      labels:
        app: kafka-connector
    spec:
      containers:
        - name: kafka-connector
          image: quay.io/debezium/connect:1.9
          ports:
            - containerPort: 8083
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: my_connect_configs
            - name: OFFSET_STORAGE_TOPIC
              value: my_connect_offsets
            - name: STATUS_STORAGE_TOPIC
              value: my_connect_statuses
