apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres-app
data:
  POSTGRES_DB: events_db
  POSTGRES_PASSWORD: root

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-app
spec:
  type: NodePort
  selector:
    app: postgres-app
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres-app
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres
          image: quay.io/debezium/postgres:11
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
